version: "3.9"
services:
  backend:
    hostname: backend
    container_name: backend
    image: node:14-alpine
    command: .docker/entrypoint.sh
    working_dir: /app
    volumes:
      - ".:/app"
    networks:
      - web
      - core
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.rule=Host(`estiam.data2ia.dev`) && PathPrefix(`/api{regex:$$|/.*}`)"
      - "traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=backend-stripprefix"
      - "traefik.http.routers.backend.tls.domains[0].main=estiam.data2ia.dev"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myhttpchallenge"

  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - core
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - db_mongo:/data/db

networks:
  web:
    external: true
  core:
    external: true