version: "3.9"
services:
  backend:
    hostname: backend
    container_name: backend
    image: node:14-alpine
    command: .docker/entrypoint.sh
    working_dir: /app
    volumes:
      - ".:/app"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.rule=Host(`apiestiam.data2ia.dev`)"
      - "traefik.http.routers.backend.tls.domains[0].main=apiestiam.data2ia.dev"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myhttpchallenge"

networks:
  web:
    external: true